apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: puq7bfbd6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/puq7bfbd6-java-quarkus-gitops